### PR TITLE
Add master IDF to CI

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by BrettRD** [comment]
I think the CI failure is in
`"espressif/idf:latest"`, there is no branch `latest`
It should be either `idf:v4.3-dev` or `idf:master`

**Comment by pablogs9** [comment]
They do have a `latest`, chek [here](https://hub.docker.com/r/espressif/idf/tags?page=1&ordering=last_updated). But I'm not sure about the error...

Do you have a solution for this CI? If so, please contribute.

**Comment by BrettRD** [comment]
I haven't gotten very far, but I have some notes and I think someone might be able to see a little more than I can.
The `latest` docker image is causing the CI pipeline to crash when `export.sh` uses `eval` to call `idf.py` to set up bash autocomplete.
The only differences in `export.sh` between `release-4.2` and `latest` are the addition of the autocomplete section which checks if the shell is zhs, then assumes the shell is bash.
pushd and popd are not available (I wanted to try loading latest using v4.2 export.sh), so I suspect the shell isn't really bash.
The docker hub listing doesn't indicate what image the container is built from, which makes discovering the shell config tedious.

**Comment by pablogs9** [comment]
Hey, thanks for the tip, I just changed the shell to bash and now it works like a charm.

**Pull request merged**
