### PR TITLE
bugfix (#249)

### PR DESCRIPTION
**Pull request by shvass**
atomic patch no more deletes current working directory

### CODE REVIEW

**Comment by pablogs9** [comment]
Why this order change solves your issue?

**Comment by shvass** [comment]
well, here [libmicroros.mk](https://github.com/micro-ROS/micro_ros_espidf_component/pull/250/files#diff-06967651b65df7d465fbbbbb55f4d538ff5d4b6acae8d261b27f4a46b7b1fde9L135 ) the path specified to rm command happens to be the current working directory, which results in uncertain behavior. 

**just switching to another directory before performing rm fixes the issue**

**Comment by pablogs9** [comment]
@mergify backport humble iron

**Comment by 4ntn** [comment]
@mergify backport rolling

**Pull request merged**
