### PR TITLE
Add int32_publisher_custom_transport_usbcdc example

### PR DESCRIPTION
**Pull request by samuelhrqe**
This example demonstrates how to enable ROS2 communication via USB CDC and log output on the ESP32-S2.

### CODE REVIEW

**Comment by samuelhrqe** [comment]
@pablogs9 could you review my PR? I would like to contribute this example

**Comment by pablogs9** [comment]
Hello @SamuelLost, thanks for the contribution but I have no time to test it. Could you somehow add it to the CI so we can ensure it builds correctly?

**Comment by samuelhrqe** [comment]
> Hello @SamuelLost, thanks for the contribution but I have no time to test it. Could you somehow add it to the CI so we can ensure it builds correctly?

Hello, thanks for the feedback! I'll try to add it to the CI to ensure it builds correctly.

**Comment by pablogs9** [comment]
It seems that the new example is failing in CI

**Comment by samuelhrqe** [comment]
The issue was with the CI condition, I made the necessary adjustment and hopefully it won't fail this time.

**Comment by pablogs9** [comment]
@mergify backport rolling humble iron

**Comment by pablogs9** [comment]
@SamuelLost Thanks for the contribution!

**Pull request merged**
